version: '3.7'

services:

  lutrisweb:
    restart: always
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
      network: host
    env_file: .env.${DEPLOY_ENV}
    volumes:
      - type: volume
        source: web-media
        target: /app/media
        volume:
          nocopy: true
      - type: volume
        source: web-static
        target: /app/static
    depends_on:
      - lutrisdb
      - lutriscache
    extra_hosts:
      - steamcommunity.com:${STEAMCOMMUNITY_IP}

  lutrisworker:
    restart: always
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
      network: host
    env_file: .env.${DEPLOY_ENV}
    volumes:
      - type: volume
        source: web-media
        target: /app/media
        volume:
          nocopy: true
    depends_on:
      - lutrisdb
      - lutriscache
    command: celery worker -A lutrisweb.celery.app -B -l debug
    extra_hosts:
      - steamcommunity.com:${STEAMCOMMUNITY_IP}

  lutrisnginx:
    restart: always
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    image: nginx/latest
    # Expose a port for the Nginx proxy
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
    volumes:
      - web-static:/srv/static
      - web-media:/srv/media
      - web-files:/srv/files
      - web-releases:/srv/releases
    depends_on:
      - lutrisweb

  lutrisdb:
    restart: always
    image: postgres:12
    # Expose a port to do backups
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file: .env.${DEPLOY_ENV}

  lutriscache:
    restart: always
    build:
      context: config/redis
      dockerfile: Dockerfile
    volumes:
      - redisdata:/data

volumes:
  postgresql:
  web-media:
  web-static:
  web-files:
  web-releases:
  redisdata:
