version: '3.4'

services:

  lutrisweb:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
    container_name: lutrisweb
    volumes:
      - ./:/app
      - components:/app/components
      - media:/app/media
      - public:/app/public
      - vue_dist:/app/frontend/vue/dist
      - vue_static:/app/frontend/vue/static
    extra_hosts:
      - steamcommunity.com:${STEAMCOMMUNITY_IP}

    ports:
      - "8000:8000"
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - lutrisdb
      - lutriscache
      - lutrisfrontend

  lutrisfrontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
    container_name: lutrisfrontend
    volumes:
      - ./frontend/css:/app/frontend/css
      - ./frontend/image:/app/frontend/image
      - ./frontend/js:/app/frontend/js
      - ./frontend/vue/src:/app/frontend/vue/src
      - vue_dist:/app/frontend/vue/dist
      - vue_static:/app/frontend/vue/static
      - components:/app/components
      - public:/app/public
    stdin_open: true
    tty: true
    restart: on-failure

  celery_worker:
    build:
      context: .
      args:
        BOWER_PROXY: ${BOWER_PROXY}
    container_name: celery_worker
    volumes:
      - type: volume
        source: media
        target: /app/media
        volume:
          nocopy: true
    depends_on:
      - lutrisdb
      - lutriscache
    command: celery worker -A lutrisweb.celery.app -B -l info
    extra_hosts:
      - steamcommunity.com:${STEAMCOMMUNITY_IP}

  lutrisdb:
    image: postgres:12
    container_name: lutrisdb
    expose:
      - "5430"
    command: -p 5430
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'lutris'
      POSTGRES_USER: 'lutris'
      POSTGRES_PASSWORD: 'admin'

  lutriscache:
    container_name: lutriscache
    restart: on-failure
    image: redis:6.0.1
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  postgresql:
  media:
  redisdata:
  public:
  components:
  vue_static:
  vue_dist:
