version: '3.4'

services:

  lutrisweb:
    build:
      context: .
      dockerfile: travis.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
      network: host
    volumes:
      - type: volume
        source: media
        target: /app/media
        volume:
          nocopy: true
      - type: bind
        source: .
        target: /app
    ports:
      - "8000:8000"
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - lutrisdb
      - lutrisfrontend
    extra_hosts:
      - steamcommunity.com:${STEAMCOMMUNITY_IP}

  lutrisfrontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        BOWER_PROXY: ${BOWER_PROXY}
      network: host
    command: bash -c "mkdir -p ./static && npm install --registry=https://registry.npm.taobao.org && npm run build:issues-dev"
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
    #stdin_open: true
    #tty: true
    restart: on-failure

  lutrisdb:
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'lutris'
      POSTGRES_USER: 'lutris'
      POSTGRES_PASSWORD: 'admin'


volumes:
  postgresql:
  media:
