# Generated by Django 2.2.12 on 2020-06-22 07:30

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20200529_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=bitfield.models.BitField((('fully_libre', '开放源代码'), ('open_engine', '使用开源引擎'), ('free', '免费'), ('freetoplay', '免费开玩'), ('pwyw', '自愿支付（PWYW）'), ('demo', '包含演示（Demo）'), ('protected', '包含反外挂措施')), default=None),
        ),
    ]
